### ISSUE TITLE
response

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam-hci#16]
Hi,

I thought for the solution and I think the reason for the error could be that the frontend and the backend are on different Ports. They could try to deliver the frontend by the backend.

Best regards 
Matthias

**Comment by ChulioZ** [comment]
It's working now.

**Comment by mschild** [comment]
Nice, what caused the issue in the end?

**Comment by ChulioZ** [comment]
We had to install the flask-cors package and then allow CORS -- then the browser would allow the request.
