### ISSUE TITLE
The longer the distance between the objects in the sentence, the lower the points for winning it

### ISSUE THREAD

**Issue by ChulioZ** [uhh-lt/cam-hci#20]
Reasoning: In a sentence with a short distance like "dog is better than cat", the probability that the sentence is actually a good one to use for comparing dog and cat is higher than in a sentence with a long distance. For example, take "dog is better at barking, men are better at typing, cat is better at climbing".

Before actually implementing this examples should be studied to get an idea of a good measurement.

**Comment by ChulioZ** [comment]
Done. We've decided not to use the actual distance between the objects within the sentence but the sentences's score returned by Elastic Search instead. We save the highest score of all sentences and for each sentence we then divide its score by this maximum and use the result as a multiplier for all points applied -- so the points are reduced for all sentences after the first one.

**Comment by alexanderpanchenko** [comment]
Makes sense to me.
